language: java
cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

install: mvn --settings .travis/settings.xml --batch-mode -DskipTests install deploy

deploy:
  provider: script
  script: mvn --settings .travis/settings.xml --batch-mode install deploy
  on:
    tags: true
    jdk: oraclejdk8

dist: trusty