language: java
jdk: openjdk8

cache:
  directories:
  - "$HOME/.m2"

install: mvn --settings .travis/settings.xml --batch-mode -DskipTests install

deploy:
  provider: script
  script: mvn --settings .travis/settings.xml --batch-mode install deploy
